# HTTP server port
port = 8091

# Directory to store video files
videoDir = 'videos'

# Video resolution
width = 1280
height = 720

# Frames per second
fps = 30

# Video processing options
recode = true     # true = recode using libx264, false = copy streams without recompression

# Platform-specific FFmpeg configurations

[linux]
ffmpegPath = '/usr/bin/ffmpeg'
ffmpegCamera = '/dev/video0'
ffmpegFormat = 'v4l2'

[windows]
# To find the camera name use:
#   ffmpeg -f dshow -list_devices true -i dummy
# Must include  video=  before the name.
ffmpegCamera = 'video=Logitech Webcam C930e'
#ffmpegCamera = 'video=OV01A'
ffmpegPath = 'ffmpeg.exe'
ffmpegFormat = 'dshow'

[wsl]
# To find the camera name use:
#   ffmpeg -f dshow -list_devices true -i dummy
# Must include  video=  before the name.
ffmpegCamera = 'video=OV01A'
ffmpegPath = '/mnt/c/ProgramData/chocolatey/bin/ffmpeg.exe'
ffmpegFormat = 'dshow'
